socrata:
  app_token: REPLACE_ME

db:
  enabled: false
  driver: REPLACE_ME
  host: REPLACE_ME
  port: REPLACE_ME
  user: REPLACE_ME
  password: REPLACE_ME
  database: REPLACE_ME
  
# I removed the following,
# so I need to make sure no scripts use it. 
#data:
  #output_epsg: 2263
  #output_shapefile: Data/shapefiles
  #output_tables: Data/tables

#curb:
  #extension_distance: 7
  #buffer_width: 15
