# env/environment.yml
name: stp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - fiona
  - rasterio
  - gdal
  - pyproj
  - sqlalchemy
  - pip
  - pip:
      - requests
      - jupyterlab
      - matplotlib
