# env/environment.yml
name: stp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - fiona
  - rasterio
  - gdal
  - pyproj
  - sqlalchemy

  # dev tools
  - black
  - flake8
  - isort
  - pytest
  
  #pip packages
  - pip
  - pip:
      - requests
      - jupyterlab
      - matplotlib
